# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v3.2.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: zulu
      - name: build
        run: ./gradlew check
      - name: publish
        if: ${{ contains(github.ref, 'refs/tags/') }}
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_OSSRHUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_OSSRHPassword: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_GitHubPackagesUsername: ${{ secrets.GITHUB_ACTOR }}
          ORG_GRADLE_PROJECT_GitHubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
      - name: codecov
        uses: codecov/codecov-action@v1.5.2
        with:
          file: processor/build/reports/jacoco/test/jacocoTestReport.xml
  mutation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: zulu
      - name: build
        run: ./gradlew pitest
      - name: striker
        run: |
          curl -X PUT "https://dashboard.stryker-mutator.io/api/reports/github.com/${GITHUB_REPOSITORY}/${GITHUB_REF/refs\/heads\/}" -H 'Content-Type: application/json' -H 'Host: dashboard.stryker-mutator.io' -H "X-Api-Key: ${{ secrets.STRYKER_TOKEN }}" -d @processor/build/reports/pitest/html2/report.js
